import { useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Archive, CheckCircle2, Download, Edit3, Eye, Pause, Play, RefreshCw, RotateCcw, Save, Send, Trash2, Upload } from 'lucide-react';
import { Panel, StatCard, VirtualTable } from './AdminPrimitives';
import type { AdminDashboardData, AdminNotification, AdminSettings, AdminStudent, AuditLogRecord, BareActAdminRecord, CurriculumAdminLesson, CurriculumAdminModule, PatternAdminRecord, QueueRecord, RoleAssignment } from '../types/admin.types';
import { lessonFormSchema, moduleFormSchema, notificationSchema, patternFormSchema, roleAssignmentSchema, settingsSchema } from '../validators/admin.validators';

type Mutations = ReturnType<typeof import('../hooks/useAdminDashboard').useAdminMutations>;

function Chart({ data, type = 'area' }: { data: Array<{ label: string; value: number; secondary?: number }>; type?: 'area' | 'bar' | 'line' }) {
  return <div className="bam-chart"><ResponsiveContainer width="100%" height={220}>{type === 'bar' ? <BarChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="label" /><YAxis /><Tooltip /><Bar dataKey="value" fill="#276749" /><Bar dataKey="secondary" fill="#d97706" /></BarChart> : type === 'line' ? <LineChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="label" /><YAxis /><Tooltip /><Line type="monotone" dataKey="value" stroke="#276749" strokeWidth={2} /></LineChart> : <AreaChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="label" /><YAxis /><Tooltip /><Area type="monotone" dataKey="value" stroke="#276749" fill="#d9f0df" /></AreaChart>}</ResponsiveContainer></div>;
}

function matchesQuery(row: unknown, query: string) {
  return JSON.stringify(row).toLowerCase().includes(query.toLowerCase());
}

export function OverviewSection({ data }: { data: AdminDashboardData }) {
  return <div className="bam-section"><section className="bam-stat-grid">{data.metrics.map((metric) => <StatCard key={metric.id} label={metric.label} value={metric.value} unit={metric.unit} trend={metric.trend} state={metric.state} />)}</section><div className="bam-grid two"><Panel title="Lesson Completion Trend"><Chart data={data.trends.lessons} /></Panel><Panel title="Mastery Progression"><Chart data={data.trends.mastery} type="line" /></Panel><Panel title="AI Usage"><Chart data={data.trends.aiUsage} type="bar" /></Panel><Panel title="Queue Depth vs Failures"><Chart data={data.trends.queues} type="bar" /></Panel></div>{data.unavailableSources.length > 0 && <Panel title="Unavailable Sources"><ul className="bam-warning-list">{data.unavailableSources.slice(0, 8).map((source) => <li key={source}>{source}</li>)}</ul></Panel>}</div>;
}

export function StudentsSection({ data, query, mutations }: { data: AdminDashboardData; query: string; mutations: Mutations }) {
  const rows = useMemo(() => data.students.filter((student) => matchesQuery(student, query)), [data.students, query]);
  const exportRows = () => {
    const blob = new Blob([JSON.stringify(rows, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = 'bare-act-mentor-student-progress.json';
    anchor.click();
    URL.revokeObjectURL(url);
  };
  return <Panel title="Student Management" action={<button type="button" onClick={exportRows}><Download size={14} />Export progress</button>}><VirtualTable<AdminStudent> rows={rows} columns={[{ key: 'student', label: 'Student', render: (s) => <strong>{s.name}<em>{s.email}</em></strong> }, { key: 'mastery', label: 'Mastery', render: (s) => `${s.mastery}%` }, { key: 'weaknesses', label: 'Weaknesses', render: (s) => s.weaknessCount }, { key: 'drafting', label: 'Drafting / AI', render: (s) => `${s.lessonsCompleted} lessons · ${s.aiInteractions} turns` }, { key: 'status', label: 'Status', render: (s) => <span className={`bam-badge ${s.status}`}>{s.status}</span> }, { key: 'actions', label: 'Actions', render: (s) => <div className="bam-actions"><button type="button" title="View profile"><Eye size={14} /></button><button type="button" onClick={() => mutations.studentAction.mutate({ id: s.id, action: 'reset' })}><RotateCcw size={14} />Reset</button><button type="button" onClick={() => mutations.studentAction.mutate({ id: s.id, action: 'archive' })}><Archive size={14} />Archive</button></div> }]} /></Panel>;
}

export function CurriculumSection({ data, mutations }: { data: AdminDashboardData; mutations: Mutations }) {
  const moduleForm = useForm({ defaultValues: { title: '', description: '', order: data.modules.length + 1, status: 'draft', prerequisites: '', masteryCriteria: '' } });
  const lessonForm = useForm({ defaultValues: { moduleId: data.modules[0]?.id ?? '', title: '', objectives: '', prerequisites: '', estimatedMinutes: 35, status: 'draft' } });
  return <div className="bam-grid two"><Panel title="Modules" action={<span>{data.modules.length} modules</span>}><VirtualTable<CurriculumAdminModule> rows={data.modules} columns={[{ key: 'title', label: 'Module', render: (m) => <strong>{m.order}. {m.title}<em>{m.description}</em></strong> }, { key: 'lessons', label: 'Lessons', render: (m) => m.lessonCount }, { key: 'status', label: 'Status', render: (m) => <span className={`bam-badge ${m.status}`}>{m.status}</span> }, { key: 'actions', label: 'Actions', render: () => <div className="bam-actions"><button type="button"><Edit3 size={14} />Edit</button><button type="button"><Trash2 size={14} />Delete</button></div> }]} /></Panel><Panel title="Create / Edit Module"><form className="bam-form" onSubmit={moduleForm.handleSubmit((values) => mutations.saveModule.mutate(moduleFormSchema.parse(values)))}><input placeholder="Module title" {...moduleForm.register('title')} /><textarea placeholder="Description" {...moduleForm.register('description')} /><input type="number" {...moduleForm.register('order')} /><select {...moduleForm.register('status')}><option value="draft">Draft</option><option value="published">Published</option><option value="unpublished">Unpublished</option></select><textarea placeholder="Prerequisites, one per line" {...moduleForm.register('prerequisites')} /><textarea placeholder="Mastery criteria" {...moduleForm.register('masteryCriteria')} /><button type="submit"><Save size={14} />Save module</button></form></Panel><Panel title="Lessons"><VirtualTable<CurriculumAdminLesson> rows={data.lessons} columns={[{ key: 'title', label: 'Lesson', render: (l) => <strong>{l.title}<em>{l.objectives.join('; ')}</em></strong> }, { key: 'module', label: 'Module', render: (l) => l.moduleId }, { key: 'time', label: 'Time', render: (l) => `${l.estimatedMinutes}m` }, { key: 'status', label: 'Status', render: (l) => <span className={`bam-badge ${l.status}`}>{l.status}</span> }]} /></Panel><Panel title="Create / Edit Lesson"><form className="bam-form" onSubmit={lessonForm.handleSubmit((values) => mutations.saveLesson.mutate(lessonFormSchema.parse(values)))}><select {...lessonForm.register('moduleId')}>{data.modules.map((m) => <option key={m.id} value={m.id}>{m.title}</option>)}</select><input placeholder="Lesson title" {...lessonForm.register('title')} /><textarea placeholder="Objectives" {...lessonForm.register('objectives')} /><textarea placeholder="Prerequisites" {...lessonForm.register('prerequisites')} /><input type="number" {...lessonForm.register('estimatedMinutes')} /><select {...lessonForm.register('status')}><option value="draft">Draft</option><option value="published">Published</option><option value="locked">Locked</option></select><button type="submit"><Save size={14} />Save lesson</button></form></Panel></div>;
}

export function PatternSection({ data, query, mutations }: { data: AdminDashboardData; query: string; mutations: Mutations }) {
  const form = useForm({ defaultValues: { name: '', category: 'Legislative drafting', difficulty: 'intermediate', status: 'draft', checklist: '', commonMistakes: '', examples: '' } });
  const rows = data.patterns.filter((row) => matchesQuery(row, query));
  return <div className="bam-grid two"><Panel title="Pattern Library Manager"><VirtualTable<PatternAdminRecord> rows={rows} columns={[{ key: 'name', label: 'Pattern', render: (p) => <strong>{p.name}<em>{p.category}</em></strong> }, { key: 'difficulty', label: 'Difficulty', render: (p) => p.difficulty }, { key: 'version', label: 'Version', render: (p) => `v${p.version}` }, { key: 'status', label: 'Status', render: (p) => <span className={`bam-badge ${p.status}`}>{p.status}</span> }, { key: 'meta', label: 'Review', render: (p) => `${p.checklist.length} checklist · ${p.commonMistakes.length} mistakes` }]} /></Panel><Panel title="Edit Pattern"><form className="bam-form" onSubmit={form.handleSubmit((values) => mutations.savePattern.mutate(patternFormSchema.parse(values)))}><input placeholder="Pattern name" {...form.register('name')} /><input placeholder="Category" {...form.register('category')} /><select {...form.register('difficulty')}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option><option value="professional">Professional</option></select><select {...form.register('status')}><option value="draft">Draft</option><option value="review">Review</option><option value="published">Published</option></select><textarea placeholder="Review checklist" {...form.register('checklist')} /><textarea placeholder="Common mistakes" {...form.register('commonMistakes')} /><textarea placeholder="Examples metadata or references" {...form.register('examples')} /><button type="submit"><Save size={14} />Save pattern</button></form></Panel></div>;
}

export function BareActSection({ data, query, mutations }: { data: AdminDashboardData; query: string; mutations: Mutations }) {
  const rows = data.bareActs.filter((row) => matchesQuery(row, query));
  return <Panel title="Bare Act Library" action={<label className="bam-upload-action"><Upload size={14} />Upload Bare Act<input type="file" accept=".pdf,.docx,.txt,.md,.markdown" /></label>}><VirtualTable<BareActAdminRecord> rows={rows} columns={[{ key: 'title', label: 'Bare Act', render: (b) => <strong>{b.title}<em>{b.jurisdiction || 'Jurisdiction metadata unavailable'}</em></strong> }, { key: 'status', label: 'Indexing', render: (b) => <span className={`bam-badge ${b.status}`}>{b.status}</span> }, { key: 'chunks', label: 'Chunks', render: (b) => b.chunkCount }, { key: 'embeddings', label: 'Embeddings', render: (b) => b.embeddingCount }, { key: 'components', label: 'Components', render: (b) => b.componentTypes.slice(0, 3).join(', ') }, { key: 'actions', label: 'Actions', render: (b) => <div className="bam-actions"><button type="button" onClick={() => mutations.reindexBareAct.mutate(b.id)}><RefreshCw size={14} />Re-index</button><button type="button"><Eye size={14} />Inspect</button></div> }]} /></Panel>;
}

export function AiSection({ data }: { data: AdminDashboardData }) {
  return <div className="bam-grid two"><Panel title="AI Monitoring Records"><VirtualTable rows={data.ai} columns={[{ key: 'label', label: 'Signal', render: (r) => <strong>{r.label}<em>{r.kind}</em></strong> }, { key: 'status', label: 'Status', render: (r) => <span className={`bam-badge ${r.status}`}>{r.status}</span> }, { key: 'count', label: 'Count', render: (r) => r.count }, { key: 'tokens', label: 'Tokens', render: (r) => r.tokens ?? '—' }, { key: 'cost', label: 'Cost', render: (r) => r.cost ? `$${r.cost.toFixed(2)}` : '—' }]} /></Panel><Panel title="Token Usage"><Chart data={data.trends.aiUsage} type="bar" /></Panel><Panel title="Cost Analytics"><Chart data={data.trends.costs} /></Panel><Panel title="Validation & Safety"><ul className="bam-warning-list">{data.ai.map((item) => <li key={item.id}>{item.label}: {item.status}</li>)}</ul></Panel></div>;
}

export function QueueSection({ data, mutations }: { data: AdminDashboardData; mutations: Mutations }) {
  return <Panel title="Queue Monitoring"><VirtualTable<QueueRecord> rows={data.queues} columns={[{ key: 'name', label: 'Queue', render: (q) => <strong>{q.name}<em>{q.lastEventAt || 'No recent event'}</em></strong> }, { key: 'depth', label: 'Depth', render: (q) => q.depth }, { key: 'failed', label: 'Failed', render: (q) => q.failed }, { key: 'throughput', label: 'Throughput', render: (q) => q.throughput }, { key: 'state', label: 'State', render: (q) => <span className={`bam-badge ${q.state}`}>{q.state}</span> }, { key: 'actions', label: 'Actions', render: (q) => <div className="bam-actions"><button type="button" onClick={() => mutations.queueAction.mutate({ queueName: q.name, action: 'retry' })}><RefreshCw size={14} />Retry</button><button type="button" onClick={() => mutations.queueAction.mutate({ queueName: q.name, action: 'pause' })}><Pause size={14} />Pause</button><button type="button" onClick={() => mutations.queueAction.mutate({ queueName: q.name, action: 'resume' })}><Play size={14} />Resume</button></div> }]} /></Panel>;
}

export function AnalyticsSection({ data }: { data: AdminDashboardData }) {
  return <div className="bam-grid two"><Panel title="Lesson Completion"><Chart data={data.trends.lessons} type="bar" /></Panel><Panel title="Mastery Progression"><Chart data={data.trends.mastery} type="line" /></Panel><Panel title="AI Usage"><Chart data={data.trends.aiUsage} type="bar" /></Panel><Panel title="Queue Analytics"><Chart data={data.trends.queues} type="bar" /></Panel></div>;
}

export function SettingsSection({ data, mutations }: { data: AdminDashboardData; mutations: Mutations }) {
  const form = useForm<AdminSettings>({ defaultValues: data.settings });
  return <Panel title="System Settings"><form className="bam-form settings" onSubmit={form.handleSubmit((values) => mutations.saveSettings.mutate(settingsSchema.parse(values)))}><label>OpenAI model<input {...form.register('model')} /></label><label>Temperature<input type="number" step="0.1" {...form.register('temperature')} /></label><label>Max tokens<input type="number" {...form.register('maxTokens')} /></label><label>Prompt version<input {...form.register('promptVersion')} /></label><label>Embedding model<input {...form.register('embeddingModel')} /></label><label>Vector top K<input type="number" {...form.register('vectorTopK')} /></label><label>Rate limit / minute<input type="number" {...form.register('rateLimitPerMinute')} /></label><label><input type="checkbox" {...form.register('streaming')} /> Streaming enabled</label><label><input type="checkbox" {...form.register('maintenanceMode')} /> Maintenance mode</label><button type="submit"><Save size={14} />Save settings</button></form></Panel>;
}

export function AuditSection({ data, query }: { data: AdminDashboardData; query: string }) {
  const rows = data.auditLogs.filter((row) => matchesQuery(row, query));
  return <Panel title="Audit Logs"><VirtualTable<AuditLogRecord> rows={rows} columns={[{ key: 'actor', label: 'Actor', render: (a) => a.actor }, { key: 'action', label: 'Action', render: (a) => <strong>{a.action}<em>{a.target}</em></strong> }, { key: 'severity', label: 'Severity', render: (a) => <span className={`bam-badge ${a.severity}`}>{a.severity}</span> }, { key: 'created', label: 'Created', render: (a) => new Date(a.createdAt).toLocaleString() }]} /></Panel>;
}

export function RoleSection({ data, mutations }: { data: AdminDashboardData; mutations: Mutations }) {
  const form = useForm({ defaultValues: { email: '', role: 'instructor', permissions: 'curriculum:read\ncurriculum:write\nstudents:read' } });
  return <div className="bam-grid two"><Panel title="Permissions Matrix"><VirtualTable<RoleAssignment> rows={data.roles} columns={[{ key: 'email', label: 'User', render: (r) => <strong>{r.email}<em>{r.permissions.join(', ')}</em></strong> }, { key: 'role', label: 'Role', render: (r) => <span className={`bam-badge ${r.role}`}>{r.role}</span> }, { key: 'updated', label: 'Updated', render: (r) => r.updatedAt ? new Date(r.updatedAt).toLocaleString() : '—' }]} /></Panel><Panel title="Assign Role"><form className="bam-form" onSubmit={form.handleSubmit((values) => mutations.assignRole.mutate(roleAssignmentSchema.parse(values)))}><input placeholder="email@legatrixon.com" {...form.register('email')} /><select {...form.register('role')}><option value="admin">Admin</option><option value="instructor">Instructor</option><option value="student">Student</option></select><textarea placeholder="Permissions" {...form.register('permissions')} /><button type="submit"><CheckCircle2 size={14} />Assign role</button></form></Panel></div>;
}

export function NotificationSection({ data, mutations }: { data: AdminDashboardData; mutations: Mutations }) {
  const form = useForm({ defaultValues: { title: '', body: '', audience: 'students', severity: 'info', published: true } });
  return <div className="bam-grid two"><Panel title="Notifications"><VirtualTable<AdminNotification> rows={data.notifications} columns={[{ key: 'title', label: 'Notification', render: (n) => <strong>{n.title}<em>{n.body}</em></strong> }, { key: 'audience', label: 'Audience', render: (n) => n.audience }, { key: 'severity', label: 'Severity', render: (n) => <span className={`bam-badge ${n.severity}`}>{n.severity}</span> }, { key: 'published', label: 'Published', render: (n) => n.published ? 'Yes' : 'No' }]} /></Panel><Panel title="Create Announcement"><form className="bam-form" onSubmit={form.handleSubmit((values) => mutations.publishNotification.mutate(notificationSchema.parse(values)))}><input placeholder="Title" {...form.register('title')} /><textarea placeholder="Message" {...form.register('body')} /><select {...form.register('audience')}><option value="all">All</option><option value="students">Students</option><option value="instructors">Instructors</option><option value="admins">Admins</option></select><select {...form.register('severity')}><option value="info">Info</option><option value="warning">Warning</option><option value="maintenance">Maintenance</option></select><label><input type="checkbox" {...form.register('published')} /> Publish immediately</label><button type="submit"><Send size={14} />Save notification</button></form></Panel></div>;
}
