import { BadGatewayException } from '@nestjs/common';
import { AcademyProfessorService } from './academy-professor.service';
const answer='The authority shall apply the provision within its defined scope because the legal effect and procedure must remain certain.';
const response=(status:'correct'|'partial'|'incorrect',conceptUnderstanding:number,legalAccuracy:number,draftingLogic:number)=>JSON.stringify({status,overallScore:Math.round((conceptUnderstanding+legalAccuracy+draftingLogic+86+84)/5),conceptUnderstanding,legalAccuracy,draftingLogic,professionalLanguage:86,structuralLogic:84,strengths:['Identifies the legal actor.'],mistakes:status==='correct'?[]:['The legal effect needs more precision.'],feedback:status==='correct'?'The lesson concept is mastered.':'Revise the legal effect and explain why it follows.',improvedAnswer:'Clarify the operative effect and its controlled scope.',unlockNextLesson:status==='correct'});
describe('AcademyProfessorService evaluation pipeline',()=>{
 it('returns the exact schema and unlocks a semantically correct answer',async()=>{const complete=jest.fn().mockResolvedValue({content:response('correct',90,84,88),provider:'test',model:'test',responseTimeMs:1});const result=await new AcademyProfessorService({complete} as any).review('u',1,answer);expect(result).toMatchObject({status:'correct',conceptUnderstanding:90,legalAccuracy:84,draftingLogic:88,unlockNextLesson:true});expect(result.strengths).toHaveLength(1)});
 it('returns partial and keeps progression open for an almost-correct answer',async()=>{const complete=jest.fn().mockResolvedValue({content:response('partial',78,82,74),provider:'test',model:'test',responseTimeMs:1});const result=await new AcademyProfessorService({complete} as any).review('u',1,answer);expect(result.status).toBe('partial');expect(result.unlockNextLesson).toBe(true);expect(result.mistakes.length).toBeGreaterThan(0)});
 it('returns incorrect and keeps progression open for a non-mastered answer',async()=>{const complete=jest.fn().mockResolvedValue({content:response('incorrect',30,25,20),provider:'test',model:'test',responseTimeMs:1});const result=await new AcademyProfessorService({complete} as any).review('u',1,answer);expect(result.status).toBe('incorrect');expect(result.unlockNextLesson).toBe(true)});
 it('downgrades a claimed correct status when any required score is below 80',async()=>{const complete=jest.fn().mockResolvedValue({content:response('correct',90,79,90),provider:'test',model:'test',responseTimeMs:1});const result=await new AcademyProfessorService({complete} as any).review('u',1,answer);expect(result.status).toBe('partial');expect(result.unlockNextLesson).toBe(true)});
 it('repairs fenced JSON with smart quotes and trailing commas',async()=>{const raw='```json\n'+response('correct',90,90,90).replace(/"/g,'”').replace(/}$/ ,',}')+'\n```';const complete=jest.fn().mockResolvedValue({content:raw,provider:'test',model:'test',responseTimeMs:1});const result=await new AcademyProfessorService({complete} as any).review('u',1,answer);expect(result.status).toBe('correct')});
 it('retries invalid JSON and succeeds on a later valid response',async()=>{const complete=jest.fn().mockResolvedValueOnce({content:'not json',provider:'test',model:'test',responseTimeMs:1}).mockResolvedValueOnce({content:response('partial',70,75,72),provider:'test',model:'test',responseTimeMs:1});const result=await new AcademyProfessorService({complete} as any).review('u',1,answer);expect(complete).toHaveBeenCalledTimes(2);expect(result.status).toBe('partial')});
 it('throws a retryable server error only after all three provider attempts fail',async()=>{const complete=jest.fn().mockRejectedValue(new Error('provider offline'));await expect(new AcademyProfessorService({complete} as any).review('u',1,answer)).rejects.toThrow(BadGatewayException);expect(complete).toHaveBeenCalledTimes(3)});
});